sudo: false
language: node_js
node_js:
  - '7'
install:
  - npm install
script:
  - npm run lint
before_deploy:
  - export CLOUDSDK_CORE_DISABLE_PROMPTS=1;
  - curl https://sdk.cloud.google.com | bash;
  - exec -l $SHELL
  - gcloud --quiet version
  - openssl aes-256-cbc -K $encrypted_476ecf204a07_key
    -iv $encrypted_476ecf204a07_iv
    -in gcloud-service-keys.json.enc -out gcloud-service-keys.json -d
  - gcloud auth activate-service-account --key-file gcloud-service-key.json
  - gcloud config set project devops-174104
deploy:
  - provider: script
    script:
    - ls
    skip_cleanup: true
    on:
      branch: master
