language: node_js
node_js:
  - '7'
install:
  - npm install
script:
  - npm run lint
before_deploy:
  - npm run build
deploy:
  provider: s3
  access_key_id: AKIAIXOFIDNR7BVDU3BA
  secret_access_key:
    secure: q4GQCTtOr7GLhcvODvpyG2XP3cBTXHE4oLFSp3rJu8JonIi6fjJG6cFcDUNEOcYnmcKHrQH4mOVUIFcMFMXStWC/cN8Yk2aE9J+3PVOkNmJCdUtc9c+n79UbMRgIqIUxcjJONanUtEw9BlkSj/YAW+oCnWCYJHLt+K4qsCEgpLBatAvtDGzKB9s3sSpNO15W0iVX5JjjHk6TEasPjlRWbOdAVsZqul8uQnMQpD7R0av+t2nqUh4JrwOSkCxI+6LCb471tVI18DYG0aiAlw8mWLy4mhTrOlZ7t6LBO1cqGtNZOnpgfcLQQ1a5ghjza/vS7akrOk8FtFFvf0NdDRMKBTJ3ze4WXnNJNxnmI+ksC8+0RwZmLuBTGxRXcDW1c5w69bCqBYSaSnmxUsAaWzXGCK6JWYsil/5AN4kvu/v49eTMYLW8oNBaSFCUkYHDGL1JKzqVqeXPj3WRgKBcormcID6ZImjE/haHBW9filltFfrn1T2cFwzeoR7xJlVYn6y4jBdSUhSnvmfRYrFdtKVmAibNhItm5cURqWJfVIcZjOohK/j7oV0mZEw39neASKT0cIOK5yZc1dkwjRiPfYQF5dM8bD06qFYiiji2ARt+v16LNDfU1KiuFCOnE5xaiWsqjfgtBQ/4xwLQJ1iYaE+xGuZvCPS4cnq065bmAh17MQs=
  bucket: G4SPreVzoIy+RgswnfuNZUgchimAoppDcLM/enlispencercwood-tetris
  local-dir: dist
  acl: public_read
  skip_cleanup: true
